//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingMaterials.DbStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderContent
    {
        public int OrderContentId { get; set; }
        public int OrderID { get; set; }
        public int ProductId { get; set; }
        public int ProductAmount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
